### ISSUE TITLE
Chrome launched, but didn't give us a WebSocket URL before we timed out

### ISSUE THREAD

**Issue by seanpianka** [rust-headless-chrome/rust-headless-chrome#344]
I'm seeing the following panic when trying to launch a chromium browser in an alpine docker container:
```rust
    Finished dev [unoptimized + debuginfo] target(s) in 6m 46s
     Running `target/debug/headless`
created launch options for browser
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chrome launched, but didn't give us a WebSocket URL before we timed out', src/main.rs:11:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## `src/main.rs`

This is the only code file needed. It'll panic on the final unwrap.

```rust
fn main() {
    use headless_chrome::{Browser, LaunchOptionsBuilder};

    let launch_options = LaunchOptionsBuilder::default()
        .window_size(Some((1280, 1280)))
        .headless(true)
        .port(Some(8001))
        .build()
        .unwrap();
    println!("created launch options for browser");
    let browser = Browser::new(launch_options).unwrap();
    println!("launched browser");
}
```

## `Cargo.toml`

This has my fork with a fix for the `rustls` compiler error on the current `master`.

```toml
[package]
name = "chrome-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
headless_chrome = { version = "1.0.0", default-features = false, features = ["rustls"] }
```

# Rust Version
```
$ rustup show
Default host: x86_64-unknown-linux-musl
rustup home:  /usr/local/rustup

installed toolchains
--------------------

nightly-2022-10-21-x86_64-unknown-linux-musl
1.65.0-x86_64-unknown-linux-musl (default)

active toolchain
----------------

1.65.0-x86_64-unknown-linux-musl (default)
rustc 1.65.0 (897e37553 2022-11-02)
```

## Build Environment `Dockerfile`
```dockerfile
FROM rust:alpine
RUN apk add bash alpine musl-dev openssl-dev vim curl alpine-sdk chromium chromium-chromedriver
RUN rustup target add x86_64-unknown-linux-musl
RUN rustup component add clippy llvm-tools-preview
```

You can use this as a runtime environment:

```shell
$ docker build -t chrome-test:latest .
$ docker run -v $(pwd):/opt/app -w /opt/app -it chrome-test:latest /bin/bash
$ cargo run
```

I tried opening a port explicitly for with iptables, but it had no effect: `$ iptables -A INPUT -p tcp --dport 8001 -j ACCEPT`

```rust
    Finished dev [unoptimized + debuginfo] target(s) in 6m 46s
     Running `target/debug/headless`
created launch options for browser
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chrome launched, but didn't give us a WebSocket URL before we timed out', src/main.rs:11:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by seanpianka** [comment]
Is it possible to disable the debug port entirely?

**Comment by seanpianka** [comment]
What's odd is that the above code fails when `start_process` fails to bind any port between 8000 and 9000 (specifically in the `port_is_available` function within `src/browser/process.rs`). However, in the same Alpine build environment, I'm able to bind to this port explicitly using the same function call that is the body of the `port_is_available` function.

Replace the `src/main.rs` from above with the following code, and it succeeds:

```rust
use std::net;
fn main() {
    println!("{}", net::TcpListener::bind(("127.0.0.1", 8001)).is_ok());
    println!("{}", net::TcpListener::bind(("0.0.0.0", 8001)).is_ok());
}
```

However, attempting to bind to this same port using the `LaunchOptions` builder method `.port(Some(8001))` fails after some failure to bind.

**Comment by mdrokz** [comment]
> Is it possible to disable the debug port entirely?

im not even sure what it does i havent done any research about it, and this issue seems similar to this #261 #267 #300

**Comment by seanpianka** [comment]
Well, it seems simple enough, but I hadn't read the console output from chromium when running my example:
> [2023-02-24T23:42:02Z TRACE headless_chrome::browser::process] Chrome output: [0224/234202.994319:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

I simply added `.sandbox(false)` to the browser builder and it works under an alpine docker container/environment. I'm not sure if this closes #261, #267, or #300, but it certainly fixes my issue. 🙂

**Comment by vahidreza** [comment]
hey @seanpianka 
I'm struggling to have my code run in a docker container,
can you share somehow the Dockerfile related to the alpine ur using,
specifically how to install chrome and make it ready for the binary to use it.
tnx

**Comment by seanpianka** [comment]
> hey @seanpianka 
> 
> I'm struggling to have my code run in a docker container,
> 
> can you share somehow the Dockerfile related to the alpine ur using,
> 
> specifically how to install chrome and make it ready for the binary to use it.
> 
> tnx

My dockerfile is in the first message of this issue

**Comment by Arvmor** [comment]
Would really love to see a solution / Docker template for Debian based containers.

Still having this issue on Debian.
