### ISSUE TITLE
Windows process shell is visible each time I open `Browser::new()`

### ISSUE THREAD

**Issue by frederikhors** [rust-headless-chrome/rust-headless-chrome#371]
I'm using the below code with `v1.0.5` on `Windows 10` with `Chrome 110.0.5481.100` normally installed.

```rust
let browser_options = LaunchOptions {
  ..Default::default()
};

let browser = Browser::new(browser_options)?;

let tab = browser.new_tab()?;

let pdf_options: Option<PrintToPdfOptions> = None;

let local_pdf = tab
    .navigate_to(&html_file)?
    .wait_until_navigated()?
    .print_to_pdf(pdf_options)?;

fs::write(pdf_file, local_pdf)?;
```

Everything works except it opens a shell each time I call the above code:

![image](https://user-images.githubusercontent.com/41120635/219348757-f7c95cac-4175-493b-9885-97230a331d37.png)

I tried suggestion in https://github.com/atroche/rust-headless-chrome/issues/333 with no luck.

How can I fix this?

@ameleumit do you have suggestions?

**Comment by ameleumit** [comment]
Just try to disable default args in LaunchOptions.

let browser_options = LaunchOptions {
disable_default_args:true,
  ..Default::default()
};

**Comment by frederikhors** [comment]
Tried. The same.

**Comment by ameleumit** [comment]
Are you using headless mode ?. if not try to use headless mode. 

headless:true

**Comment by frederikhors** [comment]
Yes I already am.

**Comment by ameleumit** [comment]
i tried your code and had no visible chrome window.
this is the code. i am using chrome portable. (ver: 90.0.4430.212)

```
use headless_chrome::{Browser,LaunchOptions,types::PrintToPdfOptions};
use std::path::PathBuf;

pub fn main()-> Result<(), Box<dyn std::error::Error>> {
    let browser_options = LaunchOptions{
            headless:true,
            path:Some(PathBuf::from("D:/Program Files/Chrome Portable/chrome.exe")),                         //chrome portable
            user_data_dir:Some(PathBuf::from("D:/Program Files/Chrome Portable/Profile Folder")),        // chrome portable
            ..Default::default()              
        };
      let browser = Browser::new(browser_options)?;
      let tab = browser.new_tab()?;
      let pdf_options: Option<PrintToPdfOptions> = None;
      let local_pdf = tab
          .navigate_to("http://www.google.com")?
          .wait_until_navigated()?
          .print_to_pdf(pdf_options)?;
      println!("{:?}", local_pdf);
    Ok(())
}
```
cargo.toml
`headless_chrome = "1.0.5"`

i solved my previous problem by disabling default args and passing my own args.
example:

```
disable_default_args:true,
args:vec![   
            OsStr::new("--enable-features=NetworkService,NetworkServiceInProcess"),
],
```

**Comment by vootooguru** [comment]
please check it as new chrome version.
![1](https://user-images.githubusercontent.com/10230763/220520662-b119073d-b808-48d5-8c10-d63e94c302b4.jpg)
![2、](https://user-images.githubusercontent.com/10230763/220520674-ebf13c1d-1050-4e0b-b908-3499ef6aa200.jpg)

**Comment by vootooguru** [comment]
please check it at new chrome version.
![1](https://user-images.githubusercontent.com/10230763/220521290-ab973bcf-7e11-4d95-9e8d-cc28738506f8.jpg)
![2、](https://user-images.githubusercontent.com/10230763/220521303-8ca66122-6105-4985-a1ba-300cd220429e.jpg)

**Comment by vootooguru** [comment]
![image](https://user-images.githubusercontent.com/10230763/221130627-57211dfb-2c1e-42a3-a4d6-efe93064bd07.png)

this line causes the shell window to be displayed
that arg ("--enable-logging") should not be hard code.
but i don't know how to commit the fix to repo

**Comment by vootooguru** [comment]
![image](https://user-images.githubusercontent.com/10230763/221131805-aa7a5add-7438-40a4-8dda-edd4f280c5cb.png)


this line causes the shell window to be displayed
that arg ("--enable-logging") should not be hard code.
but i don't know how to commit the fix to repo

**Comment by ameleumit** [comment]
Confirmed.
Win7 no problem
Win10 `“--enable-logging”` causes new shell window.
Tested on Win10, chrome 108, headless chrome 1.0.5
