### ISSUE TITLE
Is there a way to make this method tap.type_str() type faster ?

### ISSUE THREAD

**Issue by theanh098** [rust-headless-chrome/rust-headless-chrome#394]
type_str(). This method I noticed that in headless false option, it types characters one by one it that's pretty slow. Is there any way to type input faster?

**Comment by 0xCuteSocks** [comment]
https://github.com/rust-headless-chrome/rust-headless-chrome/blob/f127f42a203468de872499b67a516d9c2bf10ed5/src/browser/tab/mod.rs#L859
use send_character instead

**Comment by theanh098** [comment]
@0xCuteSocks , Thank you so much.

**Comment by theanh098** [comment]
@0xCuteSocks. Bro. Is there any way to clear a input field or double click it ?

**Comment by 0xCuteSocks** [comment]
u assumed my gender? 

send_character empty string to input field

https://github.com/rust-headless-chrome/rust-headless-chrome/blob/f127f42a203468de872499b67a516d9c2bf10ed5/src/browser/tab/mod.rs#L965

call click_point twice

**Comment by kwinz** [comment]
Hi @0xCuteSocks,

I tried calling click_point twice, but it's not focusing the text to overwrite. It's just clicking in the middle of the text.

```
input_element.click().unwrap();
let input_element_midpoint = input_element.get_midpoint().unwrap();
tab.click_point(input_element_midpoint).unwrap();
tab.click_point(input_element_midpoint).unwrap();
```

Maybe it's not clicking fast enough to register as a double click. Is there a way to double click faster?
Or a way to send CTRL+A to select everything?

**Comment by theanh098** [comment]
@kwinz  I used to do this, u can try it
`


    let input_tag = page.find_element(input_selector).await?;

    let point = input_tag
      .scroll_into_view()
      .await?
      .clickable_point()
      .await?;

    let cmd = DispatchMouseEventParams::builder()
      .x(point.x)
      .y(point.y)
      .button(MouseButton::Left)
      .click_count(2);

    page
      .move_mouse(point)
      .await?
      .execute(
        cmd
          .clone()
          .r#type(DispatchMouseEventType::MousePressed)
          .build()
          .unwrap(),
      )
      .await?;

    page
      .execute(
        cmd
          .r#type(DispatchMouseEventType::MouseReleased)
          .build()
          .unwrap(),
      )
      .await?;
      
     input_tag.press_key("Backspace").await?;
`
