### ISSUE TITLE
how `add_event_listener` use async?

### ISSUE THREAD

**Issue by baerwang** [rust-headless-chrome/rust-headless-chrome#449]
![img_v3_0276_77562b5a-8249-4133-b40b-f162c4fb126g](https://github.com/rust-headless-chrome/rust-headless-chrome/assets/52104949/6ff38626-e706-43bd-8577-e9c2fed556d9)

![image](https://github.com/rust-headless-chrome/rust-headless-chrome/assets/52104949/6b35e685-86a1-4007-9072-d3b0c324ea0a)

**Comment by yoramdelangen** [comment]
Best solution I currenlty came up with is using:
```rust
let rt = tokio::runtime::Runtime::new()?;

rt.block_on(async { .... });
```
