### ISSUE TITLE
Waiting is not async so doesn't work well with Tokio runtime

### ISSUE THREAD

**Issue by kingsleyh** [rust-headless-chrome/rust-headless-chrome#462]
I believe when waiting for things to happen it's using a blocking sleep - I would like to execute headless chrome within a Tokio runtime as async - are there any ways to do this currently? or any plans to support an async sleep / wait?

**Comment by mirsella** [comment]
This crate is not async, you can use thread or tokio spawn blocking. There are other crate with who use async

**Comment by kingsleyh** [comment]
thanks - I used tokio spawn blocking
