### ISSUE TITLE
There are no available ports between 8000 and 9000 for debugging

### ISSUE THREAD

**Issue by Ahmard** [rust-headless-chrome/rust-headless-chrome#487]
Hey guys, I've been trying to run this package with "chromium-browser" on ubuntu and I keep getting below error
There are no available ports between 8000 and 9000 for debugging

Please help

**Comment by Ahmard** [comment]
Fixed.
Thanks :)

**Comment by eng-cc** [comment]
> Fixed. Thanks :)

 I encountered the same problem, how did I fix it?

**Comment by Ahmard** [comment]
You just need define the port manually.
Below works for me.

```rust
let browser = Browser::new(headless_chrome::browser::LaunchOptions {
    // Specify a different port
    port: Some(9967),
    sandbox: false,
    ..Default::default()
})?;
```
