### ISSUE TITLE
Can't navigate: Unable to make method calls because underlying connection is closed

### ISSUE THREAD

**Issue by WindLeaf233** [rust-headless-chrome/rust-headless-chrome#490]
Simplified codes:
```rust
fn main() {
    let tab = init_browser_tab().unwrap();
    let sc = take_screenshot(&tab, "https://google.com/").unwrap();                 // Crashed here
    // ...
}

fn init_browser_tab() -> Result<Arc<Tab>, Error> {
    let options = LaunchOptionsBuilder::default()
        .window_size(Some((1920, 1080)))
        .build();
    match Browser::new(options?) {
        Ok(browser) => browser.new_tab(),
        Err(error) => Err(error),
    }
}

fn take_screenshot(tab: &Arc<Tab>, url: &str) -> Result<Vec<u8>, Error> {
    if let Err(e) = tab.navigate_to(url)?.wait_until_navigated() {                // Method Tab::navigate_to panicked
        println!("Failed to navigate to page: {}", e);
    }
    sleep(Duration::from_secs(5));
    tab.capture_screenshot(CaptureScreenshotFormatOption::Png, Some(32), None, true)
}
```

It crashed like this:
```
called `Result::unwrap()` on an `Err` value: Unable to make method calls because underlying connection is closed
```

I've tried to use the `if let` statement to catch the error and print it out, but it crashed every time I ran the program.

What is wrong with my codes or network?

**Some seemingly useful information:**

I used to think it a problem about SSL and my network (I use system proxy by the way), but changing **https** to **http** and disabling my proxy did nothing.

Besides, I did use VSCode connecting to my WSL (Windows Subsystem Linux) where I code.

<details>
<summary>
Stack backtrace (click to show)
</summary>
<pre><code>
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.86/src/backtrace.rs:27:14
   1: <T as core::convert::Into<U>>::into
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/convert/mod.rs:759:9
   2: headless_chrome::browser::transport::Transport::call_method
             at /home/user/.cargo/git/checkouts/rust-headless-chrome-f0e3e1c64237edb7/731df7f/src/browser/transport/mod.rs:130:24
   3: headless_chrome::browser::transport::Transport::call_method_on_target
             at /home/user/.cargo/git/checkouts/rust-headless-chrome-f0e3e1c64237edb7/731df7f/src/browser/transport/mod.rs:189:9
   4: headless_chrome::browser::tab::Tab::call_method
             at /home/user/.cargo/git/checkouts/rust-headless-chrome-f0e3e1c64237edb7/731df7f/src/browser/tab/mod.rs:508:22
   5: headless_chrome::browser::tab::Tab::navigate_to
             at /home/user/.cargo/git/checkouts/rust-headless-chrome-f0e3e1c64237edb7/731df7f/src/browser/tab/mod.rs:538:29
   6: project::screenshot::take_screenshot
             at ./src/screenshot.rs:20:21
   7: project::main
             at ./src/main.rs:16:14
   8: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
   9: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:155:18
  10: std::rt::lang_start::{{closure}}
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:159:18
  11: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:284:13
  12: std::panicking::try::do_call
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
  13: std::panicking::try
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
  14: std::panic::catch_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
  15: std::rt::lang_start_internal::{{closure}}
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:141:48
  16: std::panicking::try::do_call
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
  17: std::panicking::try
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
  18: std::panic::catch_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
  19: std::rt::lang_start_internal
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:141:20
  20: std::rt::lang_start
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:158:17
  21: main
  22: <unknown>
  23: __libc_start_main
  24: _start
stack backtrace:
   0: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1654:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1077:23
   4: project::main
             at ./src/main.rs:16:14
   5: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
</code></pre>
</details>

**Comment by Naoray** [comment]
Had the same issue. I m new to rust so I can’t explain with 100% certainty, my best guess is that the browser variable is dropped as soon as  the init_browser_tab method returns the tab. Try to return both tab and browser or only return the browser and your issue should be fixed

**Comment by WindLeaf233** [comment]
> Had the same issue. I m new to rust so I can’t explain with 100% certainty, my best guess is that the browser variable is dropped as soon as the init_browser_tab method returns the tab. Try to return both tab and browser or only return the browser and your issue should be fixed

Thanks! This does fix the problem :)
