### ISSUE TITLE
[Bug] Chrome devtool is aroused when using `Browser::default` or `LaunchOptions`'s default builder

### ISSUE THREAD

**Issue by Embers-of-the-Fire** [rust-headless-chrome/rust-headless-chrome#500]
## Summary

`LaunchOptions.devtools` has mismatched default value configuration, between custom default & builder default.

## Source code snippet

```rust
// browser/process.rs L82-88,94-96

/// Represents the way in which Chrome is run. By default it will search for a Chrome
/// binary on the system, use an available port for debugging, and start in headless mode.
#[derive(Clone, Debug, Builder)]
pub struct LaunchOptions<'a> {
    /// Determines whether to run headless version of the browser. Defaults to true.
    #[builder(default = "true")]
    pub headless: bool,

    /// Automatically open devtools for tabs. Forces headless to be false
    #[builder(default = "true")]
    pub devtools: bool,
```

```rust
// browser/process.rs L179-183

impl<'a> Default for LaunchOptions<'a> {
    fn default() -> Self {
        LaunchOptions {
            headless: true,
            devtools: false,
```

Obviously the `devtools` field should be `false` by default, but the `builder` attribute set the default value to `true`.

## Influenced behavior

Running chrome with default configuration will lead to "headful" chrome app instead of "headless" one.

## Platform and version

Platform: Windows 11
Rustc version: rustc 1.79.0 (129f3b996 2024-06-10)
Cargo version: cargo 1.79.0 (ffa9cf99a 2024-06-03)
Library version: `headless_chrome = "1.0.12"`

## Fast fix without changing library code

Use

```rust
Browser::new(
    LaunchOptions::default_builder()
        .devtools(false)
        .build()?,
)?
```

instead of

```rust
Browser::default()?
```

**Comment by mirsella** [comment]
and if this is intentional, this is breaking change as the default now open a window

**Comment by edulix** [comment]
We were also hit with this in production. Please guys, remove `devtools` default. A crate called `rust-headless-chrome` that had `headless: true` as a default should probably not perform a patch update where the default changes to `headless: false`.

**Comment by actengage** [comment]
We ran into this into production as well. This killed a bit of time just to figure out. Many thanks for the solution in this thread.

**Comment by Embers-of-the-Fire** [comment]
UPD: The issue name has been modified for search engines to find based on the behavior.
