### ISSUE TITLE
Type text faster?

### ISSUE THREAD

**Issue by subdigital** [rust-headless-chrome/rust-headless-chrome#504]
I may be missing something obvious here, but with this code:

```rust
        tab.wait_for_element("#frm_login")?.type_into(user)?;
```

The typing is _so slow_. I enabled tracing logs to see what it's doing and it seems like it's waiting for confirmation of every single keyDown & keyUp event?

Is there a way to set the string in one go, or improve the speed of this typing behavior somehow? (I didn't see any way to configure a delay here, and it doesn't look like one is implemented anywhere in the `call_method` function.

I did see `send_character`, which doesn't emit all the same events, but figured there might be an easier way than this.

**Comment by nandreau** [comment]
You can use javascript to input it faster like that :

```
tab.evaluate(
        &format!(
            r#"
            document.querySelector('#input-id').value = '{value}';
            "#
        ),
        false,
    )
```

**Comment by subdigital** [comment]
This is what I ended up doing, thanks!
