### ISSUE TITLE
Calling any logging from JS Code won't trigger the LogEntryAdded event

### ISSUE THREAD

**Issue by savire** [rust-headless-chrome/rust-headless-chrome#520]
Hi guys,

```
tab.enable_runtime();
tab.enable_log();
tab.enable_debugger();

tab.add_event_listener(Arc::new(move |event: &Event| {
  match event {
     Event::LogEntryAdded(evt) => {
       println!(">> JS LOG : [{:?}] {:?}", evt.params.entry.level, evt.params.entry.text);
     }
     _ => { }
  }
}));

let jcode = r#"
(async () => {
  console.log("Just info log")
  console.warn("Some warning")
  console.error("Still nothing")
})();  
"#;

let code = match tab.evaluate(jcode, true) {
  Ok(code) => code,
  Err(err) => return err.to_string(),
};
```

Calling any logging from JS Code like this won't trigger the **LogEntryAdded** event. I'm using the latest version.

**Comment by guapodero** [comment]
Same issue here. There's a reference to the solution in an old issue, though it didn't appear in the discussion.
https://github.com/rust-headless-chrome/rust-headless-chrome/issues/277#issue-1056648093

Here's what worked for me:
```
tab.enable_runtime().unwrap();
tab.add_event_listener(Arc::new(move |event: &Event| match event {
    Event::RuntimeConsoleAPICalled(event) => {
        println!(
            ">> JS LOG : [{:?}] {:?}",
            event.params.Type,
            event
                .params
                .args
                .get(0)
                .unwrap()
                .value
                .as_ref()
                .unwrap()
                .as_str()
                .unwrap()
        );
    }
    _ => {}
}))
.unwrap();

let jcode = r#"
(async () => {
  console.log("Just info log")
  console.warn("Some warning")
  console.error("Still nothing")
})();
"#;

let code = match tab.evaluate(jcode, true) {
  Ok(code) => format!("{code:?}"),
  Err(err) => return err.to_string(),
};
```

**Comment by savire** [comment]
> Same issue here. There's a reference to the solution in an old issue, though it didn't appear in the discussion. [#277 (comment)](https://github.com/rust-headless-chrome/rust-headless-chrome/issues/277#issue-1056648093)
> 
> Here's what worked for me:
> 
> ```
> tab.enable_runtime().unwrap();
> tab.add_event_listener(Arc::new(move |event: &Event| match event {
>     Event::RuntimeConsoleAPICalled(event) => {
>         println!(
>             ">> JS LOG : [{:?}] {:?}",
>             event.params.Type,
>             event
>                 .params
>                 .args
>                 .get(0)
>                 .unwrap()
>                 .value
>                 .as_ref()
>                 .unwrap()
>                 .as_str()
>                 .unwrap()
>         );
>     }
>     _ => {}
> }))
> .unwrap();
> 
> let jcode = r#"
> (async () => {
>   console.log("Just info log")
>   console.warn("Some warning")
>   console.error("Still nothing")
> })();
> "#;
> 
> let code = match tab.evaluate(jcode, true) {
>   Ok(code) => format!("{code:?}"),
>   Err(err) => return err.to_string(),
> };
> ```

Hi mate,
Thank you. That is mostly solved the issue. Although seems like it has some finicky details that needs to be further handled.

Seems like the pairing with existing chrome runtime installed will cause so many troubles too. Like with the latest chrome the headless flag are not working anymore. I did saw there is a notice from the popup when its non headless saying that some of the parameters is causing issues like this one. Its indeed causing stability issue like fetching API abruptly ended without returning proper error code.

![image](https://github.com/user-attachments/assets/d68ea34c-514f-4892-8084-4ae95ac627bf)

Anyhow thank you so much for the help. Seems like the project are not quite active. It will be hard to maintain it for production. Quite sad that this is probably the only solution for rust at least for now.

**Comment by guapodero** [comment]
Glad I could help you. If you get stuck again then maybe give chromiumoxide a try.

**Comment by savire** [comment]
> Glad I could help you. If you get stuck again then maybe give chromiumoxide a try.

Sure will try and take a look at that project.
